### ISSUE TITLE
'controls' does not exist on type 'AbstractControl'.

### ISSUE THREAD

**Issue by HasuNoHana** [PacktPublishing/Angular---The-Complete-Guide-2021-Edition#5]
Hello there,
I'm working on an app from chapter 15 reactive approach and I stumbled upon an error: "'controls' does not exist on type 'AbstractControl'."  My project doesent recognise controls on object signupForm.get('hobbies'). I'm currently on video number 15.27. There in HTML code we create a loop while creating FormArray for hobbies: " *ngFor="let hobbyControl of signupForm.get('hobbies').controls; let i = index" ". 

I used value instead but then it is reading just one letter from input before going out of text field, to enter more than one letter we have to click there again. I found someone having similar issue but unfortunately it wasn't solved: https://stackoverflow.com/questions/68769332/how-to-solve-issue-when-text-input-loses-focus-after-typing-one-character-in-ang

Could you help me?

**Comment by Sonakshis** [comment]
There is a lecture in the course (between “Reactive: Grouping Controls” and “Reactive: Arrays of Form Controls (FormArray)”) called “Fixing a Bug”. It is a text lecture with the following content:

In the next lecture, we'll add some code to access the controls of our form array:
*ngFor="let hobbyControl of signupForm.get('hobbies').controls; let i = index"

This code will fail as of the latest Angular version. You can fix it easily though. Outsource the "get the controls" logic into a method of your component code (the .ts file):

getControls() {
  return (<FormArray>this.signupForm.get('hobbies')).controls;
}

In the template, you can then use:
*ngFor="let hobbyControl of getControls(); let i = index"

Alternatively, you can set up a getter and use an alternative type casting syntax:

get controls() {
  return (this.signupForm.get('hobbies') as FormArray).controls;
}
and then in the template:
*ngFor="let hobbyControl of controls; let i = index"

This adjustment is required due to the way TS works and Angular parses your templates (it doesn't understand TS there).
